# Generated by Django 4.0.5 on 2022-07-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('deporte', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
                ('nacimiento', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('numero_socio', models.CharField(max_length=50)),
                ('numero_dni', models.CharField(max_length=50)),
                ('nacimiento', models.CharField(max_length=50)),
                ('deporte', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
    ]
